List<Map<String, dynamic>> movieDetails = [
  {
    "name": "CMBYN",
    "poster": "https://picsum.photos/100",
    "isMovie": true,
    "release": 2015,
    "source": "google",
    "isWatched": true,
    "genre": <String>{"romance", "comedy", "drama"},
  },
  {
    "name": "CMBYN",
    "poster": "https://picsum.photos/100",
    "isMovie": true,
    "release": 2015,
    "source": "google",
    "isWatched": true,
    "genre": <String>{"romance", "comedy", "drama"},
  },
  {
    "name": "CMBYN",
    "poster": "https://picsum.photos/100",
    "isMovie": true,
    "release": 2015,
    "source": "google",
    "isWatched": true,
    "genre": <String>{"romance", "comedy", "drama"},
  },
  {
    "name": "CMBYN",
    "poster": "https://picsum.photos/100",
    "isMovie": true,
    "release": 2015,
    "source": "google",
    "isWatched": true,
    "genre": <String>{"romance", "comedy", "drama"},
  },
  {
    "name": "CMBYN",
    "poster": "https://picsum.photos/100",
    "isMovie": true,
    "release": 2015,
    "source": "google",
    "isWatched": true,
    "genre": <String>{"romance", "comedy", "drama"},
  },
];
