List<String> name = [
  'Alia Ali',
  'Usama Sarwar',
  'Bano Qudsia',
  'Ali Ahmad',
  'Alina Saleem',
  'Qamtum Julia',
  'Alia Ali',
  'Usama Sarwar',
  'Bano Qudsia',
  'Ali Ahmad',
  'Alina Saleem',
  'Qamtum Julia',
  'Alia Ali',
  'Usama Sarwar',
  'Bano Qudsia',
  'Ali Ahmad',
  'Alina Saleem',
  'Qamtum Julia',
];

List<String> chats = [
  'Whats\'s Up dear?',
  'Hi',
  'Okay, bye',
  'Khatam, ta ta',
  'Bye Bye',
  'Nice to meet you.',
  'Welcome dear',
  'Whats\'s Up dear?',
  'Hi',
  'Okay, bye',
  'Khatam, ta ta',
  'Bye Bye',
  'Nice to meet you.',
  'Welcome dear',
  'Whats\'s Up dear?',
  'Hi',
  'Okay, bye',
  'Khatam, ta ta',
];
